/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars: import('@docusaurus/plugin-content-docs').SidebarsConfig = {
  pnx_docs_content_sidebar: [
    {type: 'autogenerated', dirName: '.'}
  ],
};

export default sidebars;
