/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
  // Misc content sidebar
  misc_content_sidebar: [
    {type: 'autogenerated', dirName: 'misc'},
    {
      type: 'category',
      label: 'Tutorial',
      items: ['misc/art-assets', 'misc/intro'],
    },
  ],
  /**
   *  Do not use unless necessary !!!
   *  By default, Docusaurus generates a sidebar from the docs folder structure 
   **/
  //default_sidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
